apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: docs

  template:
    metadata:
      labels:
        app: docs

    spec:
      containers:
        - name: docs
          image: nginx:latest

          ports:
            - containerPort: 80

          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html

      volumes:
        - name: html
          configMap:
            name: docs-html
