apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaler
  namespace: default

spec:
  scaleTargetRef:
    name: backend

  pollingInterval: 15
  cooldownPeriod: 60

  minReplicaCount: 1
  maxReplicaCount: 5

  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
