apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins

spec:
  interval: 10m

  chart:
    spec:
      chart: jenkins
      version: "5.8.60"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system

  values:
    controller:
      image:
        repository: jenkins/jenkins
        tag: "2.555.3-jdk21"

      serviceType: NodePort
      nodePort: 32000

      admin:
        username: admin
        password: Admin123!

      installPlugins:
        - git
        - workflow-aggregator
        - docker-workflow
        - docker-commons
        - credentials-binding

      persistence:
        enabled: true
        size: 10Gi

    agent:
      enabled: false
