apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins

spec:
  interval: 10m

  chart:
    spec:
      chart: jenkins
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system

  values:
    controller:
      image:
        registry: docker.io
        repository: ruchithabc/jenkins-docker
        tag: latest

      serviceType: NodePort
      nodePort: 32000

      admin:
        username: admin
        password: Admin123!

      installPlugins:
        - kubernetes
        - workflow-aggregator
        - git
        - docker-workflow
        - configuration-as-code

      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1Gi

      persistence:
        enabled: true
        size: 10Gi

      containerEnv:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock

      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock

    agent:
      enabled: true
