apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins

spec:
  interval: 10m

  chart:
    spec:
      chart: jenkins
      version: "5.8.60"
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system

  values:
    controller:
      image:
        registry: docker.io
        repository: diyacmenezes202/jenkins
        tag: latest

      serviceType: NodePort
      nodePort: 32000

      admin:
        username: admin
        password: Admin123!

      installPlugins:
        - git
        - workflow-aggregator
        - docker-workflow

      persistence:
        enabled: true
        size: 10Gi

      containerEnv:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock

      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket

      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock

    agent:
      enabled: false
