apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmstack
  namespace: monitoring

spec:
  interval: 10m

  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system

  values:
    vmalert:
      enabled: false

    alertmanager:
      enabled: false

    grafana:
      enabled: true
      replicaCount: 1
      adminUser: admin
      adminPassword: MySecurePassword123
      persistence:
        enabled: true
        size: 5Gi
      service:
        type: NodePort
        nodePort: 30300

    kube-state-metrics:
      enabled: true
      replicaCount: 1

    prometheus-node-exporter:
      enabled: true
