apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmstack
  namespace: monitoring

spec:
  interval: 10m

  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: vm
        namespace: flux-system

  values:
    vmalert:
      enabled: false

    alertmanager:
      enabled: false

    grafana:
      enabled: true
      replicaCount: 1
      adminUser: admin
      adminPassword: MySecurePassword123

      persistence:
        enabled: true
        size: 5Gi

      service:
        type: NodePort
        nodePort: 30300

      initChownData:
        enabled: false

      podSecurityContext:
        fsGroup: 472

      securityContext:
        runAsUser: 472
        runAsGroup: 472

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    vmsingle:
      enabled: true
      spec:
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi

    vmagent:
      spec:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

    kube-state-metrics:
      enabled: true
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi

    prometheus-node-exporter:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
